version: "3.8"

services:
  mongo:
    image: mongo:8.0
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  payment-service:
    build: .
    image: payment-service
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "8084:8080"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
